trigger:
  branches:
    include:
      - main-iatec

pr: none

pool:
  name: IATec-Builds-Agents

variables:
  buildConfiguration: 'Release'

steps:
  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'Dotnet build'

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        $xml = [xml](Get-Content src/MediatR/MediatR.csproj)
        $version = ($xml.Project.PropertyGroup | Where-Object { $_.PackageVersion } | Select-Object -First 1).PackageVersion
        Write-Host "Package version: $version"
    displayName: 'Display package version'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'pack'
      packagesToPack: '**/MediatR.csproj'
      packDirectory: '$(Build.ArtifactStagingDirectory)'
      nobuild: true
      versioningScheme: 'off'
    displayName: 'Pack NuGet package'

  - task: NuGetCommand@2
    displayName: 'NuGet push'
    inputs:
      command: push
      publishVstsFeed: 'IATec.Community'
      allowPackageConflicts: true